# Generated by Django 5.2.7 on 2025-10-31 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.store')),
            ],
            options={
                'db_table': 'inventory',
                'indexes': [models.Index(fields=['product_id', 'store_id'], name='inventory_product_62b3c6_idx'), models.Index(fields=['store_id'], name='inventory_store_i_4a639d_idx')],
                'unique_together': {('product_id', 'store_id')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Manual Adjustment'), ('layaway_create', 'Layaway Create'), ('layaway_fulfill', 'Layaway Fulfill'), ('damage', 'Damage/Loss')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.store')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'indexes': [models.Index(fields=['product_id', 'store_id'], name='inventory_t_product_a5d1ad_idx'), models.Index(fields=['created_at'], name='inventory_t_created_f087fb_idx'), models.Index(fields=['transaction_type'], name='inventory_t_transac_a372b6_idx')],
            },
        ),
    ]
