# Generated by Django 5.2.7 on 2025-10-31 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('total_discount_given', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.store')),
            ],
            options={
                'db_table': 'daily_sales_reports',
                'indexes': [models.Index(fields=['store_id', 'date'], name='daily_sales_store_i_908f02_idx'), models.Index(fields=['date'], name='daily_sales_date_cd32fd_idx')],
                'unique_together': {('store_id', 'date')},
            },
        ),
    ]
