# Generated by Django 5.2.7 on 2025-10-31 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_reason', models.TextField()),
                ('total_refund', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_sale_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.store')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
            options={
                'db_table': 'returns',
            },
        ),
        migrations.CreateModel(
            name='ReturnLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_returned', models.IntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('return_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='returns.return')),
            ],
            options={
                'db_table': 'return_line_items',
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['store_id', 'status'], name='returns_store_i_fba3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['original_sale_id'], name='returns_origina_adf84a_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['created_at'], name='returns_created_a8860b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnlineitem',
            index=models.Index(fields=['return_id'], name='return_line_return__7d5bae_idx'),
        ),
        migrations.AddIndex(
            model_name='returnlineitem',
            index=models.Index(fields=['product_id'], name='return_line_product_0bd4f2_idx'),
        ),
    ]
